### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by abdulrahman1s** [TheMaestro1s/better-revolt.js#8]
### TODO
- [X] Generate documentation with typdoc
- [X] Host the documentation site on free hosting
- [ ] Add description for methods and properties
- [X] Add examples
